#!/usr/bin/env bash
# Local twin of the ci-ansible.yml ansible-lint composite: lints this
# repo's Ansible content (roles/, playbooks/, ansible.cfg) through the
# controller venv, reusing the exact helper and config resolution CI runs
# - .github/actions/ansible-lint/ansible-lint.sh - so the local pre-push
# bar cannot drift from CI's. Wired into run-lint-yaml-and-bash.sh so a
# full local lint keeps covering ansible-lint once Common-Automation's
# delegated runner drops its own step (feature 20 re-homes the gate here).
#
# Execution model: ansible-lint - and the bare `ansible-config` it shells
# out to - live in the WSL controller venv ops/bootstrap-controller
# provisions, not on Windows. Two consequences:
#
#   1. Under Git Bash / Cygwin (how the .bat launchers and the menu start
#      this) the venv is unreachable, so re-exec self inside the WSL
#      default distro - the same distro bootstrap-controller drives via
#      `wsl --`. uname -s is "Linux" inside WSL and on native-Linux CI, so
#      the re-exec fires exactly once and never loops.
#   2. The venv must be *activated* (bin/ on PATH), not python-invoked,
#      because the helper calls a bare `ansible-lint` which in turn execs
#      a bare `ansible-config`.
#
# Auto-skips with a ::notice:: (exit 0) when the venv is absent so a host
# that never bootstrapped the controller still gets a green lint run; the
# helper itself owns the complementary no-Ansible-content auto-skip.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

# Windows launcher bridge - mirrors ops/_run-playbook.sh. See the header
# for why the venv is only reachable inside WSL.
case "$(uname -s)" in
    MINGW* | MSYS* | CYGWIN*)
        if ! command -v wsl.exe >/dev/null 2>&1; then
            echo "::notice::launched under Git Bash but wsl.exe is unavailable; skipping ansible-lint (bootstrap the WSL controller to enable it)"
            exit 0
        fi
        # Translate this script's own dir /c/... (Git Bash) -> /mnt/c/...
        # (WSL mount) so wsl.exe can re-run it by absolute path. \L
        # lowercases the drive letter (GNU sed ships with Git Bash).
        wsl_script="$(printf '%s' "${script_dir}" | sed -E 's#^/([A-Za-z])/#/mnt/\L\1/#')/run-lint-ansible.sh"
        # MSYS2 rewrites /-leading args into Windows paths when launching a
        # Windows .exe, which would corrupt the /mnt path; disable that for
        # the exec so wsl.exe sees it verbatim.
        export MSYS2_ARG_CONV_EXCL='*'
        export MSYS_NO_PATHCONV=1
        exec wsl.exe -- bash "${wsl_script}"
        ;;
    *)
        # WSL ("Linux" uname) or native-Linux CI: the venv is present, so
        # run in place. This is the path the controller and CI take.
        ;;
esac

venv_activate="${repo_root}/.venv/bin/activate"
if [[ ! -f "${venv_activate}" ]]; then
    echo "::notice::no controller venv at ${repo_root}/.venv - run ops/bootstrap-controller.ps1; skipping ansible-lint"
    exit 0
fi

# Activate (not python-invoke) so the helper's bare `ansible-lint`, and
# the `ansible-config` it execs, resolve from the venv. The activate
# script touches vars that `set -u` would flag as unbound (PS1), so relax
# -u across the source only.
set +u
# shellcheck source=/dev/null  # runtime path, generated by the bootstrap
source "${venv_activate}"
set -u

# Mirror ansible.cfg's `roles_path = roles`, the way CI's self branch does
# (ci-ansible.yml exports ANSIBLE_ROLES_PATH=<self>/roles). On the /mnt/c
# drvfs mount Ansible silently ignores ansible.cfg, so a role that
# references another repo-local role by short name would otherwise fail to
# resolve during the lint. See ops/_ansible-env.sh for the full drvfs
# cfg-ignore rationale.
export ANSIBLE_ROLES_PATH="${repo_root}/roles"

exec bash "${repo_root}/.github/actions/ansible-lint/ansible-lint.sh" "${repo_root}"
